@php
    $score = (int) ($audit['overall_score'] ?? 0);
    $scoreColor = $score >= 80 ? '#16a34a' : ($score >= 50 ? '#d97706' : '#dc2626');
    $sevColor = ['good' => '#16a34a', 'warning' => '#d97706', 'critical' => '#dc2626'];
@endphp
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: 'DejaVu Sans', sans-serif; }
        body { color: #1e293b; font-size: 12px; line-height: 1.5; margin: 0; }
        .header { background: #0f172a; color: #fff; padding: 28px 32px; }
        .header .brand { font-size: 20px; font-weight: bold; }
        .header .brand span { color: #38bdf8; }
        .header .sub { color: #94a3b8; font-size: 11px; margin-top: 4px; }
        .wrap { padding: 24px 32px; }
        .target { color: #475569; font-size: 11px; word-break: break-all; }
        .score-box { text-align: center; border: 2px solid {{ $scoreColor }}; border-radius: 10px; padding: 14px; width: 150px; }
        .score-num { font-size: 34px; font-weight: bold; color: {{ $scoreColor }}; }
        .score-label { font-size: 10px; color: #64748b; text-transform: uppercase; letter-spacing: 1px; }
        h2 { font-size: 14px; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin: 22px 0 10px; }
        table { width: 100%; border-collapse: collapse; }
        th { text-align: left; font-size: 10px; text-transform: uppercase; color: #64748b; padding: 6px 8px; border-bottom: 2px solid #e2e8f0; }
        td { padding: 8px; border-bottom: 1px solid #f1f5f9; vertical-align: top; }
        .sev { font-weight: bold; font-size: 10px; text-transform: uppercase; }
        .win { padding: 5px 0; }
        .footer { margin-top: 26px; padding-top: 12px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand">Opti<span>Tide</span></div>
        <div class="sub">Instant SEO Audit Report</div>
    </div>

    <div class="wrap">
        <table style="margin-bottom: 8px;">
            <tr>
                <td style="border: none; padding: 0; vertical-align: middle;">
                    <div style="font-size: 15px; font-weight: bold;">SEO Audit</div>
                    <div class="target">{{ $lead->website_url }}</div>
                    <div style="color:#94a3b8; font-size: 10px; margin-top: 4px;">Prepared {{ now()->format('j F Y') }}</div>
                </td>
                <td style="border: none; padding: 0; text-align: right; vertical-align: middle;">
                    <div class="score-box" style="display: inline-block;">
                        <div class="score-num">{{ $score }}</div>
                        <div class="score-label">Overall score</div>
                    </div>
                </td>
            </tr>
        </table>

        <p style="color:#334155;">{{ $audit['summary'] ?? 'No summary available.' }}</p>

        <h2>Findings</h2>
        @if (! empty($audit['findings']))
            <table>
                <thead>
                    <tr><th style="width: 20%;">Area</th><th style="width: 12%;">Status</th><th>Detail &amp; recommendation</th></tr>
                </thead>
                <tbody>
                    @foreach ($audit['findings'] as $finding)
                        @php($sev = $finding['severity'] ?? 'warning')
                        <tr>
                            <td><strong>{{ $finding['area'] ?? '—' }}</strong></td>
                            <td><span class="sev" style="color: {{ $sevColor[$sev] ?? '#64748b' }};">{{ ucfirst($sev) }}</span></td>
                            <td>
                                {{ $finding['detail'] ?? '' }}
                                @if (! empty($finding['recommendation']))
                                    <div style="color:#0369a1; margin-top: 3px;"><strong>Fix:</strong> {{ $finding['recommendation'] }}</div>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p style="color:#64748b;">No findings recorded.</p>
        @endif

        @if (! empty($audit['quick_wins']))
            <h2>Quick wins</h2>
            @foreach ($audit['quick_wins'] as $win)
                <div class="win">✓ {{ $win }}</div>
            @endforeach
        @endif

        <div class="footer">
            This complimentary audit was generated by OptiTide. Want us to implement these fixes?
            Reply to the email this report came from and our team will be in touch.
        </div>
    </div>
</body>
</html>
